#ifndef TOKENS_H
#define TOKENS_H

enum ree_token_type_e {
  TOKEN_NUMBER, TOKEN_IDENTIFIER, TOKEN_FUNCTION,
  TOKEN_OPERATOR, TOKEN_PAREN_OPEN, TOKEN_PAREN_CLOSE,
  TOKEN_COMMA, TOKEN_COLON, TOKEN_VARIABLE, TOKEN_END,
  TOKEN_PLUS, TOKEN_MINUS, TOKEN_MULTIPLY, TOKEN_DIVIDE,
  TOKEN_EQUALS, TOKEN_ILLEGAL, TOKEN_EOF
};

const char* ree_tokenToStr(enum ree_token_type_e tokenType);

#endif
